name: Build with Nuitka

on:
  push:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Nuitka
        run: |
          pip install nuitka

      - name: Add icon for Windows and build
        run: |
          if [[ $RUNNER_OS == 'Windows' ]]; then
            nuitka main.py --standalone --onefile --windows-icon=icons/graphon_support.ico --enable-plugin=pylint-warnings
          else
            nuitka main.py --standalone --onefile --enable-plugin=pylint-warnings
          fi
