name: Build binaries

on:
  push:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Nuitka
        run: |
          pip install nuitka

      - name: Build with Nuitka
        run: |
          nuitka main.py --standalone --onefile --enable-plugin=pylint-warnings

      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: graphon-bot-${{ matrix.os }}
          path: |
            build/*.exe
            build/*.bin
            build/*.app/**/*
